server:
  port: 9090
spring:
  cloud:
    gateway:
      routes:
        - id: useru4y
          uri: http://localhost:8083
          predicates:
            - Path=/order
        - id: use4ruy
          uri: http://localhost:8082
          predicates:
            - Path=/map/map
        - id: use4ruy
          uri: http://localhost:8081
          predicates:
            - Path=/restaurant/users

